<?php
/**
 * @file
 * dfhc_profile.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function dfhc_profile_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_suffix'.
  $field_bases['field_suffix'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_suffix',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
      'personalize' => array(
        'agent_type' => 'personalize_target',
        'enabled' => 0,
      ),
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
