<?php
/**
 * @file
 * dfhc_menus.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function dfhc_menus_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-footer-menu-1_conditions-and-treatments:conditions.
  $menu_links['menu-footer-menu-1_conditions-and-treatments:conditions'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'conditions',
    'router_path' => 'conditions',
    'link_title' => 'Conditions and Treatments',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-footer-menu-1_conditions-and-treatments:conditions',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 4,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu-1_find-a-doctor:doctor-search.
  $menu_links['menu-footer-menu-1_find-a-doctor:doctor-search'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'doctor-search',
    'router_path' => 'doctor-search',
    'link_title' => 'Find a Doctor',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-footer-menu-1_find-a-doctor:doctor-search',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu-3_news:news-and-events.
  $menu_links['menu-footer-menu-3_news:news-and-events'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'news-and-events',
    'router_path' => 'news-and-events',
    'link_title' => 'News',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-footer-menu-3_news:news-and-events',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu-4_locations-and-directions:locations.
  $menu_links['menu-footer-menu-4_locations-and-directions:locations'] = array(
    'menu_name' => 'menu-footer-menu-4',
    'link_path' => 'locations',
    'router_path' => 'locations',
    'link_title' => 'Locations and Directions',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-footer-menu-4_locations-and-directions:locations',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 4,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-getting-started_conditions-and-treatments:conditions.
  $menu_links['menu-getting-started_conditions-and-treatments:conditions'] = array(
    'menu_name' => 'menu-getting-started',
    'link_path' => 'conditions',
    'router_path' => 'conditions',
    'link_title' => 'Conditions and Treatments',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-getting-started_conditions-and-treatments:conditions',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-getting-started_find-a-doctor:doctor-search.
  $menu_links['menu-getting-started_find-a-doctor:doctor-search'] = array(
    'menu_name' => 'menu-getting-started',
    'link_path' => 'doctor-search',
    'router_path' => 'doctor-search',
    'link_title' => 'Find a Doctor',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-getting-started_find-a-doctor:doctor-search',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-plan-your-arrival_locations-and-directions:locations.
  $menu_links['menu-plan-your-arrival_locations-and-directions:locations'] = array(
    'menu_name' => 'menu-plan-your-arrival',
    'link_path' => 'locations',
    'router_path' => 'locations',
    'link_title' => 'Locations and Directions',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-plan-your-arrival_locations-and-directions:locations',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-sidebar-menu_billing:news-and-events.
  $menu_links['menu-sidebar-menu_billing:news-and-events'] = array(
    'menu_name' => 'menu-sidebar-menu',
    'link_path' => 'news-and-events',
    'router_path' => 'news-and-events',
    'link_title' => 'Billing',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-sidebar-menu_billing:news-and-events',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-sidebar-menu_find-a-doctor:doctor-search.
  $menu_links['menu-sidebar-menu_find-a-doctor:doctor-search'] = array(
    'menu_name' => 'menu-sidebar-menu',
    'link_path' => 'doctor-search',
    'router_path' => 'doctor-search',
    'link_title' => 'Find a Doctor',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-sidebar-menu_find-a-doctor:doctor-search',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-top-links_search:search.
  $menu_links['menu-top-links_search:search'] = array(
    'menu_name' => 'menu-top-links',
    'link_path' => 'search',
    'router_path' => 'search',
    'link_title' => 'Search',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-top-links_search:search',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-top-links_urgent-care:<front>.
  $menu_links['menu-top-links_urgent-care:<front>'] = array(
    'menu_name' => 'menu-top-links',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Urgent Care',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-top-links_urgent-care:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: user-menu_log-out:user/logout.
  $menu_links['user-menu_log-out:user/logout'] = array(
    'menu_name' => 'user-menu',
    'link_path' => 'user/logout',
    'router_path' => 'user/logout',
    'link_title' => 'Log out',
    'options' => array(
      'identifier' => 'user-menu_log-out:user/logout',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: user-menu_login:user.
  $menu_links['user-menu_login:user'] = array(
    'menu_name' => 'user-menu',
    'link_path' => 'user/login',
    'router_path' => 'user/login',
    'link_title' => 'Login',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'user-menu_login:user',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Billing');
  t('Conditions and Treatments');
  t('Find a Doctor');
  t('Locations and Directions');
  t('Log out');
  t('Login');
  t('News');
  t('Search');
  t('Urgent Care');

  return $menu_links;
}
